'''
Fibonacci numbers are generated by setting F0 = 0, F1 = 1, and then using the formula:

Fn = Fn-1 + Fn-2
Your task is to efficiently calculate the nth element in the Fibonacci sequence and
then count the occurrence of each digit in the number. Return a list of integer pairs
sorted in descending order.

10 ≤ n ≤ 100000

Examples
f(10) = 55  # returns [(2, 5)], as there are two occurances of digit 5.

If two integers have the same count, sort them in descending order.
'''

from collections import Counter

def fib_digits(n):
    a, b = 0, 1
    for i in range(n):
        a, b = b, a+b
    return sorted(((b, int(a)) for a, b in Counter(str(a)).items()), reverse=True)

#testing
print(fib_digits(10))